import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Task App",
  description: "Generated by Masudur Rahman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-screen antialiased">{children}</body>
    </html>
  );
}
